# RHEA's CONFIGURATION FILE (YAML LANGUAGE)
---

##### FLUID PROPERTIES #####
fluid_properties:
   R_specific: 287.058                 # Specific gas constant [J/(kg·K)]
   gamma: 1.4                          # Heat capacity ratio [-]
   mu: 1.0e-5                          # Dynamic viscosity [Pa·s]
   kappa: 1.0e-3                       # Thermal conductivity [W/(m·k)]


##### PROBLEM PARAMETERS #####
problem_parameters:
   x_0: 0.0                            # Domain origin in x-direction [m]
   y_0: 0.0                            # Domain origin in y-direction [m]
   z_0: 0.0                            # Domain origin in z-direction [m]
   L_x: 1.0                            # Size of domain in x-direction [m]
   L_y: 1.0                            # Size of domain in y-direction [m]
   L_z: 1.0                            # Size of domain in z-direction [m]
   current_time: 0.0                   # Current time [s]
   final_time: 1000.0                  # Final time [s]
   output_data_file: output_data.csv   # Name of output data [-]


##### COMPUTATIONAL PARAMETERS #####
computational_parameters:
   num_grid_x: 64                      # Number of internal grid points in the x-direction
   num_grid_y: 64                      # Number of internal grid points in the y-direction
   num_grid_z: 64                      # Number of internal grid points in the z-direction
   CFL: 0.9                            # CFL coefficient
   current_time_iter: 0                # Current time iteration
   final_time_iter: 1000000            # Final time iteration
   output_iter: 100                    # Output data every given number of iterations


##### SPATIAL DISCRETIZATION #####
spatial_discretization:
   ## Evenly-spaced (dummy variable) cell centroids
   #eta_x: ( i - 0.5 )/num_grid_x
   #eta_y: ( j - 0.5 )/num_grid_y
   #eta_z: ( k - 0.5 )/num_grid_z
   # Stretching factors: x = L*eta + A*( 0.5*L - L*eta )*( 1.0 - eta )*eta, with eta = ( l - 0.5 )/num_grid 
   # A < 0: stretching at ends; A = 0: uniform; A > 0: stretching at center
   A_x: 0.0                             # Stretching factor in x-direction
   A_y: -1.915                          # Stretching factor in y-direction
   A_z: 0.0                             # Stretching factor in z-direction
   ## Unevenly-spaced (stretched) cell centroids
   #grid_x: x_0 + L_x*eta_x + A_x*( 0.5*L_x - L_x*eta_x )*( 1.0 - eta_x )*eta_x
   #grid_y: y_0 + L_y*eta_y + A_y*( 0.5*L_y - L_y*eta_y )*( 1.0 - eta_y )*eta_y
   #grid_z: z_0 + L_z*eta_z + A_z*( 0.5*L_z - L_z*eta_z )*( 1.0 - eta_z )*eta_z


##### BOUNDARY CONDITIONS #####
boundary_conditions:
   # Boundary types: Dirichlet (reflective), Neumann (transmissive), Periodic (cyclic) 
   west_bc_type: _PERIODIC_             # West boundary condition type
   east_bc_type: _PERIODIC_             # East boundary condition type
   south_bc_type: _PERIODIC_            # South boundary condition type
   north_bc_type: _PERIODIC_            # North boundary condition type
   back_bc_type: _PERIODIC_             # Back boundary condition type
   front_bc_type: _PERIODIC_            # Front boundary condition type
   west_bc_u: 0.0                       # West boundary condition u value/flux
   east_bc_u: 0.0                       # East boundary condition u value/flux
   south_bc_u: 0.0                      # South boundary condition u value/flux
   north_bc_u: 0.0                      # North boundary condition u value/flux
   back_bc_u: 0.0                       # Back boundary condition u value/flux
   front_bc_u: 0.0                      # Front boundary condition u value/flux
   west_bc_v: 0.0                       # West boundary condition v value/flux
   east_bc_v: 0.0                       # East boundary condition v value/flux
   south_bc_v: 0.0                      # South boundary condition v value/flux
   north_bc_v: 0.0                      # North boundary condition v value/flux
   back_bc_v: 0.0                       # Back boundary condition v value/flux
   front_bc_v: 0.0                      # Front boundary condition v value/flux
   west_bc_w: 0.0                       # West boundary condition w value/flux
   east_bc_w: 0.0                       # East boundary condition w value/flux
   south_bc_w: 0.0                      # South boundary condition w value/flux
   north_bc_w: 0.0                      # North boundary condition w value/flux
   back_bc_w: 0.0                       # Back boundary condition w value/flux
   front_bc_w: 0.0                      # Front boundary condition w value/flux
   west_bc_P: 0.0                       # West boundary condition P value/flux
   east_bc_P: 0.0                       # East boundary condition P value/flux
   south_bc_P: 0.0                      # South boundary condition P value/flux
   north_bc_P: 0.0                      # North boundary condition P value/flux
   back_bc_P: 0.0                       # Back boundary condition P value/flux
   front_bc_P: 0.0                      # Front boundary condition P value/flux
   west_bc_T: 0.0                       # West boundary condition T value/flux
   east_bc_T: 0.0                       # East boundary condition T value/flux
   south_bc_T: 0.0                      # South boundary condition T value/flux
   north_bc_T: 0.0                      # North boundary condition T value/flux
   back_bc_T: 0.0                       # Back boundary condition T value/flux
   front_bc_T: 0.0                      # Front boundary condition T value/flux

##### PARALLELIZATION SCHEME #####
parallelization_scheme:
   np_x: 2                              # Number of processes in x-direction
   np_y: 1                              # Number of processes in y-direction
   np_z: 1                              # Number of processes in z-direction
